---

- set_fact:
    systemd_network_dir: /etc/systemd/network

- name: set net.ipv4.conf.all.arp_filter to 1
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_filter
    value: '1'
    sysctl_set: true
    reload: true
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: set net.ipv4.conf.all.arp_ignore to 1
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_ignore
    value: '1'
    sysctl_set: true
    reload: true
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: set net.ipv4.conf.all.arp_announce to 2
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_announce
    value: '2'
    sysctl_set: true
    reload: true
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: set net.ipv4.conf.all.rp_filter to 2
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: '2'
    sysctl_set: true
    reload: true
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: "copy 10-gnbsim-access.netdev to {{ systemd_network_dir }}/10-gnbsim.netdev"
  template:
    src: roles/router/templates/10-gnbsim-access.netdev
    dest: "{{ systemd_network_dir }}/10-gnbsim-access.netdev"
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: "copy 20-gnbsim-access.network to {{ systemd_network_dir }}/20-gnbsim-access.network"
  template:
    src: roles/router/templates/20-gnbsim-access.network
    dest: "{{ systemd_network_dir }}/20-gnbsim-access.network"
  vars:
    subnet_address: "{{ gnbsim.router.macvlan.subnet_prefix }}.{{ lookup('ansible.utils.index_of', groups['gnbsim_nodes'], 'eq', inventory_hostname) }}.1/24"
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: find {{ gnbsim.router.data_iface }}'s netplan network directory
  shell: basename $(find /*/systemd/network -maxdepth 1 -not -type d -name '*{{ gnbsim.router.data_iface }}.network' -print)
  register: result
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: find {{ gnbsim.router.data_iface }}'s netplan network directory
  shell: basename $(find /*/systemd/network -maxdepth 1 -not -type d -name '*{{ gnbsim.router.data_iface }}.network' -print)
  register: result
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: "create {{ systemd_network_dir }}/{{ result.stdout }}.d"
  file:
    path: "{{ systemd_network_dir }}/{{ result.stdout }}.d"
    state: directory
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: "copy macvlan.conf to {{ systemd_network_dir }}/{{ result.stdout }}.d/macvlan-gnbsim.conf"
  template:
    src: roles/router/templates/macvlan.conf
    dest: "{{ systemd_network_dir }}/{{ result.stdout }}.d/macvlan-gnbsim.conf"
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: force systemd to reread configs
  systemd:
    daemon_reload: true
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: restart systemd-networkd
  systemd:
    name: systemd-networkd
    state: restarted
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

# TODO: use ansible's net_static_route module
- set_fact:
    subnet: "{{ core.upf.access_subnet | regex_replace('[0-9]+/24', '0/24') }}"
  when: inventory_hostname in groups['gnbsim_nodes']

- name: configure static route for upf traffic on gnbsim node
  shell: |
    ip route add {{ subnet }} via {{ core.amf.ip }}
  when: (inventory_hostname in groups['gnbsim_nodes']) and (inventory_hostname not in groups['master_nodes'])
  become: true
  ignore_errors: yes

# TODO: use ansible's net_static_route module
- name: configure static route for gnbsim traffic on aether node
  shell: |
    ip route add {{ gnbsim.router.macvlan.subnet_prefix }}.{{ lookup('ansible.utils.index_of', groups['gnbsim_nodes'], 'eq', item) }}.0/24 via {{  hostvars[item]['ansible_default_ipv4']['address'] }}
  with_items: "{{ play_hosts | intersect(groups['gnbsim_nodes']) | difference(groups['master_nodes']) }}"
  when: (inventory_hostname in groups['master_nodes'])
  become: true
  ignore_errors: yes

- name: install iptables-persistent package
  apt:
    name: iptables-persistent
    state: present
    update_cache: yes
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: create /etc/iptables directory
  file:
    path: /etc/iptables
    state: directory
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: deploy gnbsim iptables rules configuration
  template:
    src: roles/router/templates/gnbsim-iptables-rules.v4
    dest: /etc/iptables/gnbsim-rules.v4
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: copy gnbsim-iptables.service to /etc/systemd/system/gnbsim-iptables.service
  template:
    src: roles/router/templates/gnbsim-iptables.service
    dest: /etc/systemd/system/gnbsim-iptables.service
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: force systemd to reread configs
  systemd:
    daemon_reload: true
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: enable gnbsim-iptables.service
  systemd:
    name: gnbsim-iptables.service
    enabled: true
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true

- name: start gnbsim-iptables.service
  systemd:
    name: gnbsim-iptables.service
    state: started
  when: inventory_hostname in groups['gnbsim_nodes']
  become: true
